### PR TITLE
Updates for RP v5.0.0

### PR DESCRIPTION
**Pull request by jpaolini**
Report Portal had a new [release](https://github.com/reportportal/reportportal/releases).  It was a breaking change that requires some variables to be updated.  This is a quick attempt at merging [client-javascript](https://github.com/reportportal/client-javascript) in with the new updates.

### CODE REVIEW

**Comment by jpaolini** [comment]
@BorisOsipov, there are a few things that probably need to be updated.  I'm a bit strapped for time this week. Hoping this could help serve as a starting point.

**Comment by BorisOsipov** [comment]
@jpaolini my client fork already support rp v5. If you have some issues please describe them fisrt. I dont need all of weird implemented features from original client.

**Comment by BorisOsipov** [comment]
See https://github.com/BorisOsipov/reportportal-js-client/commit/8c21e972b94661ebdb00977483aedbe1d61b492e for details.

**Comment by jpaolini** [comment]
🤦‍♂ , mistake on my side.  clos

**Comment by jpaolini** [comment]
🤦‍♂ , there was an issue on my side.  went down the wrong route, just one of those days...

**Pull request closed without merging**
